# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        miniature:      # nom de notre filtre
            quality: 75 # compresse l'image à 75%
            filters:    # quel filtre build-in on applique
                thumbnail:
                    size: [600, 300] # on définit une taille 
                    mode: outbound  # on coupe les bord si le ratio n'est pas respecté
        # full:      
        #     quality: 85 
        #     filters:
        #         thumbnail:
        #             size: [1200, 1200]
        #             mode: outbound
                    